insert into place (pla_name) values('Main Stage');
insert into place (pla_name) values('Photo Stand');
insert into place (pla_name) values('Music Stand');
insert into place (pla_name) values('Environment');


insert into mediaitem (med_name, med_place_id) values ('Southbound Train - Mountain',1);
insert into mediaitem (med_name, med_place_id) values ('Mean Town Blues - Johnny Winter',1);
insert into mediaitem (med_name, med_place_id) values ('If I Were A Carpenter - Tim Hardin',1);
insert into mediaitem (med_name, med_place_id) values ('Im Going Home - Ten Years After',1);
insert into mediaitem (med_name, med_place_id) values ('Uncle Sam Blues - Jefferson Airplane',1);
insert into mediaitem (med_name, med_place_id) values ('The Who',1);
insert into mediaitem (med_name, med_place_id) values ('Credence Clearwater Revival',1);
insert into mediaitem (med_name, med_place_id) values ('Jimi Hendrix',1);
insert into mediaitem (med_name, med_place_id) values ('Love - Country Joe And The Fish',1);
insert into mediaitem (med_name, med_place_id) values ('My Crystal Spider - Sweetwater',1);
insert into mediaitem (med_name, med_place_id) values ('Why Oh Why - Sweetwater',1);
insert into mediaitem (med_name, med_place_id) values ('Woodstock Poster',2);
insert into mediaitem (med_name, med_place_id) values ('The East Village Other',2);
insert into mediaitem (med_name, med_place_id) values ('Poster 1',2);
insert into mediaitem (med_name, med_place_id) values ('Poster 2',2);
insert into mediaitem (med_name, med_place_id) values ('Poster 3',2);
insert into mediaitem (med_name, med_place_id) values ('Poster 4',2);
insert into mediaitem (med_name, med_place_id) values ('Poster 5',2);
insert into mediaitem (med_name, med_place_id) values ('Poster 6',2);
insert into mediaitem (med_name, med_place_id) values ('Poster 7',2);
insert into mediaitem (med_name, med_place_id) values ('Poster 8',2);
insert into mediaitem (med_name, med_place_id) values ('Poster 9',2);
insert into mediaitem (med_name, med_place_id) values ('Image 1',2);
insert into mediaitem (med_name, med_place_id) values ('Image 2',2);
insert into mediaitem (med_name, med_place_id) values ('Image 3',2);
insert into mediaitem (med_name, med_place_id) values ('Image 4',2);
insert into mediaitem (med_name, med_place_id) values ('Image 5',2);
insert into mediaitem (med_name, med_place_id) values ('Image 6',2);
insert into mediaitem (med_name, med_place_id) values ('Image 7',2);
insert into mediaitem (med_name, med_place_id) values ('Image 8',2);
insert into mediaitem (med_name, med_place_id) values ('Image 9',2);
insert into mediaitem (med_name, med_place_id) values ('Freedom - Richie Havens',3);
insert into mediaitem (med_name, med_place_id) values ('The "Fish" Cheer - Country Joe And The Fish',3);
insert into mediaitem (med_name, med_place_id) values ('Rock & Soul Music - Country Joe And The Fish',3);
insert into mediaitem (med_name, med_place_id) values ('Love Machine - Country Joe And The Fish',3);
insert into mediaitem (med_name, med_place_id) values ('Country Joe Into - Country Joe McDonald',3);
insert into mediaitem (med_name, med_place_id) values ('I Feel Like Im Fixin To Die - Country Joe McDonald',3);
insert into mediaitem (med_name, med_place_id) values ('Coming Into Los Angeles - Arlo Guthrie',3);
insert into mediaitem (med_name, med_place_id) values ('Suite: Judy Blue Eyes - Crosby, Stills, Nash & Young',3);
insert into mediaitem (med_name, med_place_id) values ('Marrakesh Express - Crosby, Stills, Nash & Young',3);
insert into mediaitem (med_name, med_place_id) values ('Pre Roads Down - Crosby, Stills, Nash & Young',3);
insert into mediaitem (med_name, med_place_id) values ('Guinnevere - Crosby, Stills, Nash & Young',3);
insert into mediaitem (med_name, med_place_id) values ('Going Up The Country - Canned Heat',3);
insert into mediaitem (med_name, med_place_id) values ('Rollin Blues - Canned Heat',3);
insert into mediaitem (med_name, med_place_id) values ('Woodstock Boogie - Canned Heat',3);
insert into mediaitem (med_name, med_place_id) values ('Dance To The Music - Sly & The Family Stone',3);
insert into mediaitem (med_name, med_place_id) values ('Bad Moon Rising - Credence Clearwater Revival',3);
insert into mediaitem (med_name, med_place_id) values ('Green River - Credence Clearwater Revival',3);
insert into mediaitem (med_name, med_place_id) values ('Born On The Bayou - Credence Clearwater Revival',3);
insert into mediaitem (med_name, med_place_id) values ('Proud Mary - Credence Clearwater Revival',3);
insert into mediaitem (med_name, med_place_id) values ('I Put A Spell On You - Credence Clearwater Revival',3);
insert into mediaitem (med_name, med_place_id) values ('The Letter - Joe Cocker',3);
insert into mediaitem (med_name, med_place_id) values ('With A Little Help From My Friends - Joe Cocker',3);
insert into mediaitem (med_name, med_place_id) values ('Hitchcock Railway - Joe Cocker',3);
insert into mediaitem (med_name, med_place_id) values ('I Dont Need No Doctor - Joe Cocker',3);
insert into mediaitem (med_name, med_place_id) values ('Feelin Alright - Joe Cocker',3);
insert into mediaitem (med_name, med_place_id) values ('Dear Landlord - Joe Cocker',3);
insert into mediaitem (med_name, med_place_id) values ('Volunteers - Jefferson Airplane',3);
insert into mediaitem (med_name, med_place_id) values ('White Rabbit - Jefferson Airplane',3);
insert into mediaitem (med_name, med_place_id) values ('Somebody To Love - Jefferson Airplane',3);
insert into mediaitem (med_name, med_place_id) values ('Uncle Sam Blues - Jefferson Airplane',3);
insert into mediaitem (med_name, med_place_id) values ('The Other Side Of This Life - Jefferson Airplane',3);
insert into mediaitem (med_name, med_place_id) values ('Soul Sacrifice - Santana',3);
insert into mediaitem (med_name, med_place_id) values ('Savor - Santana',3);
insert into mediaitem (med_name, med_place_id) values ('Everythings Gonna Be Alright - Paul Butterfield Blues Band',3);
insert into mediaitem (med_name, med_place_id) values ('Star Spangled Banner - Jimi Hendrix',3);
insert into mediaitem (med_name, med_place_id) values ('Voodoo Child - Jimi Hendrix',3);
insert into mediaitem (med_name, med_place_id) values ('Hey Joe - Jimi Hendrix',3);
insert into mediaitem (med_name, med_place_id) values ('Fire - Jimi Hendrix',3);
insert into mediaitem (med_name, med_place_id) values ('Message To Love - Jimi Hendrix',3);
insert into mediaitem (med_name, med_place_id) values ('Im Going Home - Ten Years After',3);
insert into mediaitem (med_name, med_place_id) values ('Spoonful - Ten Years After',3);
insert into mediaitem (med_name, med_place_id) values ('More And More - Blood, Sweat & Tears',3);
insert into mediaitem (med_name, med_place_id) values ('The Letter - The Incredible String Band',3);
insert into mediaitem (med_name, med_place_id) values ('I Had A Dream - John B. Sebastian',3);
insert into mediaitem (med_name, med_place_id) values ('Spanish Fly - Keef Hartley Band',3);
insert into mediaitem (med_name, med_place_id) values ('Beatiful People - Melanie Safka',3);
insert into mediaitem (med_name, med_place_id) values ('Theme For An Imaginary Western - Mountain',3);
insert into mediaitem (med_name, med_place_id) values ('Whats Wrong - Sweetwater',3);
insert into mediaitem (med_name, med_place_id) values ('Chest Fever - The Band',3);
insert into mediaitem (med_name, med_place_id) values ('Heaven And Hell - The Who',3);
insert into mediaitem (med_name, med_place_id) values ('Drug',4);
insert into mediaitem (med_name, med_place_id) values ('Destroyable',4);

                 
insert into video (vid_length, vid_med_id, vid_perf_id) values (/*'Southbound Train - Mountain'*/'00:02:55',1,1);
insert into video (vid_length, vid_med_id, vid_perf_id) values (/*'Mean Town Blues - Johnny Winter'*/'00:05:00',2,2); 
insert into video (vid_length, vid_med_id, vid_perf_id) values (/*'If I Were A Carpenter - Tim Hardin'*/'00:02:32',3,3); 
insert into video (vid_length, vid_med_id, vid_perf_id) values (/*'Im Going Home - Ten Years After'*/'00:05:15',4,4); 
insert into video (vid_length, vid_med_id, vid_perf_id) values (/*'Uncle Sam Blues - Jefferson Airplane'*/'00:05:57',5,5); 
insert into video (vid_length, vid_med_id, vid_perf_id) values (/*'The Who'*/'00:28:11',6,6);   
insert into video (vid_length, vid_med_id, vid_perf_id) values (/*'Credence Clearwater Revival'*/'00:20:57',7,7); 
insert into video (vid_length, vid_med_id, vid_perf_id) values (/*'Jimi Hendrix'*/'01:22:17',8,8); 
insert into video (vid_length, vid_med_id, vid_perf_id) values (/*'Love - Country Joe And The Fish'*/'00:03:08',9,10); 
insert into video (vid_length, vid_med_id, vid_perf_id) values (/*'My Crystal Spider - Sweetwater'*/'00:04:59',10,11); 
insert into video (vid_length, vid_med_id, vid_perf_id) values (/*'Why Oh Why - Sweetwater'*/'00:09:16',11,);


insert into images (img_med_id, img_cat_id) values (12,1);
insert into images (img_med_id, img_cat_id) values (13,1);
insert into images (img_med_id, img_cat_id) values (14,1);
insert into images (img_med_id, img_cat_id) values (15,1);
insert into images (img_med_id, img_cat_id) values (16,1);
insert into images (img_med_id, img_cat_id) values (17,1);
insert into images (img_med_id, img_cat_id) values (18,1);
insert into images (img_med_id, img_cat_id) values (19,1);
insert into images (img_med_id, img_cat_id) values (20,1);
insert into images (img_med_id, img_cat_id) values (21,2);
insert into images (img_med_id, img_cat_id) values (22,2);
insert into images (img_med_id, img_cat_id) values (23,3);
insert into images (img_med_id, img_cat_id) values (24,3);
insert into images (img_med_id, img_cat_id) values (25,3);
insert into images (img_med_id, img_cat_id) values (26,3);
insert into images (img_med_id, img_cat_id) values (27,3);
insert into images (img_med_id, img_cat_id) values (28,3);
insert into images (img_med_id, img_cat_id) values (29,4);
insert into images (img_med_id, img_cat_id) values (30,4);


insert into imgcategory (imgcat_name) values ('Poster');
insert into imgcategory (imgcat_name) values ('Performer');
insert into imgcategory (imgcat_name) values ('Audience');
insert into imgcategory (imgcat_name) values ('Landmark');


insert into song (song_length, song_med_id, song_perf_id) values (/*'Freedom - Richie Havens'*/'00:04:34',31,12);
insert into song (song_length, song_med_id, song_perf_id) values (/*'The "Fish" Cheer - Country Joe And The Fish'*/'00:02:48',32,10);
insert into song (song_length, song_med_id, song_perf_id) values (/*'Rock & Soul Music - Country Joe And The Fish'*/'00:02:09',33,10);
insert into song (song_length, song_med_id, song_perf_id) values (/*'Love Machine - Country Joe And The Fish'*/'00:06:15',34,10);
insert into song (song_length, song_med_id, song_perf_id) values (/*'Country Joe Into - Country Joe McDonald'*/'00:07:49',35,9);
insert into song (song_length, song_med_id, song_perf_id) values (/*'I Feel Like Im Fixin To Die - Country Joe McDonald'*/'00:03:08',36,9);
insert into song (song_length, song_med_id, song_perf_id) values (/*'Coming Into Los Angeles - Arlo Guthrie'*/'00:02:18',37,13);
insert into song (song_length, song_med_id, song_perf_id) values (/*'Suite: Judy Blue Eyes - Crosby, Stills, Nash & Young'*/'00:08:06',38,14);
insert into song (song_length, song_med_id, song_perf_id) values (/*'Marrakesh Express - Crosby, Stills, Nash & Young'*/'00:02:12',39,14);
insert into song (song_length, song_med_id, song_perf_id) values (/*'Pre Roads Down - Crosby, Stills, Nash & Young'*/'00:02:47',40,14);
insert into song (song_length, song_med_id, song_perf_id) values (/*'Guinnevere - Crosby, Stills, Nash & Young'*/'00:06:01',41,14);
insert into song (song_length, song_med_id, song_perf_id) values (/*'Going Up The Country - Canned Heat'*/'00:03:06',42,15);
insert into song (song_length, song_med_id, song_perf_id) values (/*'Rollin Blues - Canned Heat'*/'00:03:57',43,15);
insert into song (song_length, song_med_id, song_perf_id) values (/*'Woodstock Boogie - Canned Heat'*/'00:05:23',44,15);
insert into song (song_length, song_med_id, song_perf_id) values (/*'Dance To The Music - Sly & The Family Stone'*/'00:02:12',45,16);
insert into song (song_length, song_med_id, song_perf_id) values (/*'Bad Moon Rising - Credence Clearwater Revival'*/'00:02:13',46,7);
insert into song (song_length, song_med_id, song_perf_id) values (/*'Green River - Credence Clearwater Revival'*/'00:03:00',47,7);
insert into song (song_length, song_med_id, song_perf_id) values (/*'Born On The Bayou - Credence Clearwater Revival'*/'00:05:34',48,7);
insert into song (song_length, song_med_id, song_perf_id) values (/*'Proud Mary - Credence Clearwater Revival'*/'00:02:57',49,7);
insert into song (song_length, song_med_id, song_perf_id) values (/*'I Put A Spell On You - Credence Clearwater Revival'*/'00:04:28',50,7);
insert into song (song_length, song_med_id, song_perf_id) values (/*'The Letter - Joe Cocker'*/'00:04:13',51,17);
insert into song (song_length, song_med_id, song_perf_id) values (/*'With A Little Help From My Friends - Joe Cocker'*/'00:07:46',52,17);
insert into song (song_length, song_med_id, song_perf_id) values (/*'Hitchcock Railway - Joe Cocker'*/'00:05:35',53,17);
insert into song (song_length, song_med_id, song_perf_id) values (/*I Dont Need No Doctor - Joe Cocker'*/'00:04:37',54,17);
insert into song (song_length, song_med_id, song_perf_id) values (/*'Feelin Alright - Joe Cocker'*/'00:04:49',55,17);
insert into song (song_length, song_med_id, song_perf_id) values (/*'Dear Landlord - Joe Cocker'*/'00:06:44',56,17);
insert into song (song_length, song_med_id, song_perf_id) values (/*'Volunteers - Jefferson Airplane'*/'00:02:46',57,5);
insert into song (song_length, song_med_id, song_perf_id) values (/*'White Rabbit - Jefferson Airplane'*/'00:02:47',58,5);
insert into song (song_length, song_med_id, song_perf_id) values (/*'Somebody To Love - Jefferson Airplane'*/'00:04:30',59,5);
insert into song (song_length, song_med_id, song_perf_id) values (/*'Uncle Sam Blues - Jefferson Airplane'*/'00:06:02',60,5);
insert into song (song_length, song_med_id, song_perf_id) values (/*'The Other Side Of This Life - Jefferson Airplane'*/'00:08:28',61,5);
insert into song (song_length, song_med_id, song_perf_id) values (/*'Soul Sacrifice - Santana'*/'00:08:06',62,18);
insert into song (song_length, song_med_id, song_perf_id) values (/*'Savor - Santana'*/'00:03:34',63,18);
insert into song (song_length, song_med_id, song_perf_id) values (/*'Everythings Gonna Be Alright - Paul Butterfield Blues Band'*/'00:05:11',64,19);
insert into song (song_length, song_med_id, song_perf_id) values (/*'Star Spangled Banner - Jimi Hendrix'*/'00:10:20',65,8);
insert into song (song_length, song_med_id, song_perf_id) values (/*'Voodoo Child - Jimi Hendrix'*/'00:11:00',66,8);
insert into song (song_length, song_med_id, song_perf_id) values (/*'Hey Joe - Jimi Hendrix'*/'00:05:25',67,8);
insert into song (song_length, song_med_id, song_perf_id) values (/*'Fire - Jimi Hendrix'*/'00:03:43',68,8);
insert into song (song_length, song_med_id, song_perf_id) values (/*'Message To Love - Jimi Hendrix'*/'00:07:20',69,8);
insert into song (song_length, song_med_id, song_perf_id) values (/*'Im Going Home - Ten Years After'*/'00:09:32',70,4);
insert into song (song_length, song_med_id, song_perf_id) values (/*'Spoonful - Ten Years After'*/'00:04:54',71,4);
insert into song (song_length, song_med_id, song_perf_id) values (/*'More And More - Blood, Sweat & Tears'*/'00:02:57',72,20);
insert into song (song_length, song_med_id, song_perf_id) values (/*'The Letter - The Incredible String Band'*/'00:03:18',73,21);
insert into song (song_length, song_med_id, song_perf_id) values (/*'I Had A Dream - John B. Sebastian'*/'00:03:06',74,22);
insert into song (song_length, song_med_id, song_perf_id) values (/*'Spanish Fly - Keef Hartley Band'*/'00:05:54',75,23);
insert into song (song_length, song_med_id, song_perf_id) values (/*'Beatiful People - Melanie Safka'*/'00:04:10',76,24);
insert into song (song_length, song_med_id, song_perf_id) values (/*'Theme For An Imaginary Western - Mountain'*/'00:05:14',77,1);
insert into song (song_length, song_med_id, song_perf_id) values (/*'Whats Wrong - Sweetwater'*/'00:10:24',78,11);
insert into song (song_length, song_med_id, song_perf_id) values (/*'Chest Fever - The Band'*/'00:06:09',79,25);
insert into song (song_length, song_med_id, song_perf_id) values (/*'Heaven And Hell - The Who'*/'00:03:50',80,6);


insert into performer (perf_name) values ('Mountain');
insert into performer (perf_name) values ('Johnny Winter');
insert into performer (perf_name) values ('Tim Hardin');
insert into performer (perf_name) values ('Ten Years After');
insert into performer (perf_name) values ('Jefferson Airplane');
insert into performer (perf_name) values ('The Who');
insert into performer (perf_name) values ('Credence Clearwater Revival');
insert into performer (perf_name) values ('Jimi Hendrix');
insert into performer (perf_name) values ('Country Joe McDonald');
insert into performer (perf_name) values ('Country Joe And The Fish');
insert into performer (perf_name) values ('Sweetwater');
insert into performer (perf_name) values ('Richie Havens');
insert into performer (perf_name) values ('Arlo Guthrie');
insert into performer (perf_name) values ('Crosby, Stills, Nash & Young');
insert into performer (perf_name) values ('Canned Heat');
insert into performer (perf_name) values ('Sly & The Family Stone');
insert into performer (perf_name) values ('Joe Cocker');
insert into performer (perf_name) values ('Santana');
insert into performer (perf_name) values ('Paul Butterfield Blues Band');
insert into performer (perf_name) values ('Blood, Sweat & Tears');
insert into performer (perf_name) values ('The Incredible String Band');
insert into performer (perf_name) values ('John B. Sebastian');
insert into performer (perf_name) values ('Keef Hartley Band');
insert into performer (perf_name) values ('Melanie Safka');
insert into performer (perf_name) values ('The Band');


insert into interactelement (interel_med_id, interel_intertype_id) values (81,1);
insert into interactelement (interel_med_id, interel_intertype_id) values (82,2);


insert into interacttype (intertype_name) values ('Drug');
insert into interacttype (intertype_name) values ('Destroyable');


insert into usermedia (umedia_med_id, umedia_usr_id) values (5,1);
insert into usermedia (umedia_med_id, umedia_usr_id) values (,1);
insert into usermedia (umedia_med_id, umedia_usr_id) values (,1);
insert into usermedia (umedia_med_id, umedia_usr_id) values (,1);
insert into usermedia (umedia_med_id, umedia_usr_id) values (,1);
insert into usermedia (umedia_med_id, umedia_usr_id) values (,1);
insert into usermedia (umedia_med_id, umedia_usr_id) values (,1);
insert into usermedia (umedia_med_id, umedia_usr_id) values (,1);
insert into usermedia (umedia_med_id, umedia_usr_id) values (,1);
insert into usermedia (umedia_med_id, umedia_usr_id) values (,1);
insert into usermedia (umedia_med_id, umedia_usr_id) values (1,2);
insert into usermedia (umedia_med_id, umedia_usr_id) values (,2);
insert into usermedia (umedia_med_id, umedia_usr_id) values (,2);
insert into usermedia (umedia_med_id, umedia_usr_id) values (,2);
insert into usermedia (umedia_med_id, umedia_usr_id) values (,2);
insert into usermedia (umedia_med_id, umedia_usr_id) values (,2);
insert into usermedia (umedia_med_id, umedia_usr_id) values (,2);
insert into usermedia (umedia_med_id, umedia_usr_id) values (,2);
insert into usermedia (umedia_med_id, umedia_usr_id) values (,2);


insert into usr (usr_name, usr_pswrd, usr_age, usr_gender, usr_avatar) values ('John Smith','123456',32,'Male',1);
insert into usr (usr_name, usr_pswrd, usr_age, usr_gender, usr_avatar) values ('Jane Doe','abcdefg',27,'Female',2);

